# -*- coding: utf-8 -*-
"""Climate_HVI_Kenya_08022026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTtT3UgSXRfgqMu4Dr-57djUm6Fafudf
"""

import ee
import pandas as pd
from google.colab import files

ee.Authenticate()
ee.Initialize(project="ee-felixol")

# Kenya boundary (GAUL level 0)
countries = ee.FeatureCollection("FAO/GAUL_SIMPLIFIED_500m/2015/level0")
kenya_fc = countries.filter(ee.Filter.eq("ADM0_NAME", "Kenya"))
kenya_geom = kenya_fc.geometry()

print("Kenya feature count:", kenya_fc.size().getInfo())

# WorldPop age-sex collection (Community Catalog)
agesex_ic = ee.ImageCollection("projects/sat-io/open-datasets/WORLDPOP/agesex")
first = ee.Image(agesex_ic.first())
has_year = "year" in first.propertyNames().getInfo()

# Age 60+ bands
female_60plus = ["f_60", "f_65", "f_70", "f_75", "f_80", "f_85", "f_90"]
male_60plus   = ["m_60", "m_65", "m_70", "m_75", "m_80", "m_85", "m_90"]

def year_image_for_kenya(year: int) -> ee.Image:
    """
    Gets a Kenya-covering image for the requested year by:
    1) filtering the year
    2) filtering to images that intersect Kenya
    3) mosaicking them into one image
    """
    if has_year:
        ic_y = agesex_ic.filter(ee.Filter.eq("year", year))
    else:
        ic_y = agesex_ic.filter(ee.Filter.stringContains("system:index", str(year)))

    ic_y_ke = ic_y.filterBounds(kenya_geom)

    n_all = ic_y.size().getInfo()
    n_ke = ic_y_ke.size().getInfo()

    if n_ke == 0:
        raise ValueError(
            f"No images intersect Kenya for year={year}. "
            f"Images for that year in collection: {n_all}."
        )

    return ee.Image(ic_y_ke.mosaic())

def safe_float(x):
    return None if x is None else float(x)

# Quick sanity test on one year first
test_year = 2020
test_img = year_image_for_kenya(test_year)
print("Test year selected. First band in mosaic:", test_img.bandNames().getInfo()[0])

# Compute totals for 2015–2030
years = list(range(2015, 2031))
rows = []

for y in years:
    img = year_image_for_kenya(y)

    female_img = img.select(female_60plus).reduce(ee.Reducer.sum()).rename("female_60plus")
    male_img   = img.select(male_60plus).reduce(ee.Reducer.sum()).rename("male_60plus")
    total_img  = female_img.add(male_img).rename("total_60plus")

    stats = total_img.addBands([female_img, male_img]).reduceRegion(
        reducer=ee.Reducer.sum(),
        geometry=kenya_geom,
        scale=100,
        bestEffort=True,
        maxPixels=1e13
    ).getInfo()

    rows.append({
        "year": y,
        "total_60plus": safe_float(stats.get("total_60plus")),
        "female_60plus": safe_float(stats.get("female_60plus")),
        "male_60plus": safe_float(stats.get("male_60plus")),
    })

df = pd.DataFrame(rows)
df

import ee
import pandas as pd
from google.colab import files

# Authenticate only if needed
try:
    ee.Initialize(project="ee-felixoluoch")
except Exception:
    ee.Authenticate()
    ee.Initialize(project="ee-felixoluoch")

# Kenya boundary from geoBoundaries (ADM0, plus ADM1 and ADM2 available)
adm0 = ee.FeatureCollection("WM/geoLab/geoBoundaries/600/ADM0")
kenya_fc = adm0.filter(ee.Filter.eq("shapeName", "Kenya"))
kenya_geom = kenya_fc.geometry()

print("geoBoundaries ADM0 Kenya feature count:", kenya_fc.size().getInfo())

# Optional: pull ADM1 and ADM2 for Kenya using the geoBoundaries country code field
kenya_shape_group = ee.String(kenya_fc.first().get("shapeGroup"))

adm1 = ee.FeatureCollection("WM/geoLab/geoBoundaries/600/ADM1").filter(
    ee.Filter.eq("shapeGroup", kenya_shape_group)
)
adm2 = ee.FeatureCollection("WM/geoLab/geoBoundaries/600/ADM2").filter(
    ee.Filter.eq("shapeGroup", kenya_shape_group)
)

print("geoBoundaries ADM1 Kenya feature count:", adm1.size().getInfo())
print("geoBoundaries ADM2 Kenya feature count:", adm2.size().getInfo())

# Optional: quick geometry area diagnostic (km2)
area_km2 = kenya_geom.area(maxError=1).divide(1e6).getInfo()
print("geoBoundaries Kenya area (km2, spherical):", area_km2)

# WorldPop age sex collection (Community Catalog)
agesex_ic = ee.ImageCollection("projects/sat-io/open-datasets/WORLDPOP/agesex")
first = ee.Image(agesex_ic.first())
has_year = "year" in first.propertyNames().getInfo()

# Age 60+ bands
female_60plus = ["f_60", "f_65", "f_70", "f_75", "f_80", "f_85", "f_90"]
male_60plus   = ["m_60", "m_65", "m_70", "m_75", "m_80", "m_85", "m_90"]

def year_image_for_kenya(year: int) -> ee.Image:
    if has_year:
        ic_y = agesex_ic.filter(ee.Filter.eq("year", year))
    else:
        ic_y = agesex_ic.filter(ee.Filter.stringContains("system:index", str(year)))

    ic_y_ke = ic_y.filterBounds(kenya_geom)

    n_all = ic_y.size().getInfo()
    n_ke = ic_y_ke.size().getInfo()

    if n_ke == 0:
        raise ValueError(
            f"No images intersect Kenya for year={year}. "
            f"Images for that year in collection: {n_all}."
        )

    return ee.Image(ic_y_ke.mosaic())

def safe_float(x):
    return None if x is None else float(x)

# Quick sanity test
test_year = 2020
test_img = year_image_for_kenya(test_year)
print("Test year selected. First band in mosaic:", test_img.bandNames().getInfo()[0])

# Compute totals for 2015 to 2030
years = list(range(2015, 2031))
rows = []

for y in years:
    img = year_image_for_kenya(y)

    female_img = img.select(female_60plus).reduce(ee.Reducer.sum()).rename("female_60plus")
    male_img   = img.select(male_60plus).reduce(ee.Reducer.sum()).rename("male_60plus")
    total_img  = female_img.add(male_img).rename("total_60plus")

    stats = total_img.addBands([female_img, male_img]).reduceRegion(
        reducer=ee.Reducer.sum(),
        geometry=kenya_geom,
        scale=100,
        bestEffort=True,
        maxPixels=1e13
    ).getInfo()

    rows.append({
        "year": y,
        "total_60plus": safe_float(stats.get("total_60plus")),
        "female_60plus": safe_float(stats.get("female_60plus")),
        "male_60plus": safe_float(stats.get("male_60plus")),
    })

df_geoBoundaries = pd.DataFrame(rows)
df_geoBoundaries



"""# Task
```python
# Initialize a list to store the results for all ADM2 regions
adm2_results = []

# Iterate through each ADM2 feature
# Convert the feature collection to a list to iterate client-side
adm2_list = adm2.toList(adm2.size())

num_adm2_regions = adm2.size().getInfo()

for i in range(num_adm2_regions):
    adm2_feature = ee.Feature(adm2_list.get(i))
    adm2_name = adm2_feature.get("shapeName").getInfo()
    adm2_geometry = adm2_feature.geometry()

    print(f"Processing ADM2: {adm2_name} ({i + 1}/{num_adm2_regions})")

    for y in years:
        # Get the WorldPop image for the current year
        # The year_image_for_kenya function already filters to Kenya's overall boundary
        img = year_image_for_kenya(y)

        # Calculate population sums for the current ADM2 geometry
        female_img = img.select(female_60plus).reduce(ee.Reducer.sum()).rename("female_60plus")
        male_img   = img.select(male_60plus).reduce(ee.Reducer.sum()).rename("male_60plus")
        total_img  = female_img.add(male_img).rename("total_60plus")

        # Reduce region for the specific ADM2 geometry
        stats = total_img.addBands([female_img, male_img]).reduceRegion(
            reducer=ee.Reducer.sum(),
            geometry=adm2_geometry, # Use the specific ADM2 geometry
            scale=100, # 100m scale for population data
            bestEffort=True,
            maxPixels=1e13
        ).getInfo()

        adm2_results.append({
            "adm2_name": adm2_name,
            "year": y,
            "total_60plus": safe_float(stats.get("total_60plus")),
            "female_60plus": safe_float(stats.get("female_60plus")),
            "male_60plus": safe_float(stats.get("male_60plus")),
        })

# Convert the results to a pandas DataFrame
df_adm2 = pd.DataFrame(adm2_results)

# Display the first few rows of the DataFrame
print("\nDataFrame containing population statistics per ADM2 region:")
print(df_adm2.head())

# Provide a download link for the CSV
csv_file_name = "kenya_adm2_60plus_population_2015-2030.csv"
df_adm2.to_csv(csv_file_name, index=False)
files.download(csv_file_name)

print(f"\nDownload complete: '{csv_file_name}'")
```

## Prepare ADM2 Data

### Subtask:
Initialize a list to store results and prepare to iterate through each ADM2 feature in Kenya's administrative boundaries.

**Reasoning**:
The subtask requires initializing a list for results, converting the Earth Engine ADM2 FeatureCollection to a client-side Python list for iteration, and getting the total number of ADM2 regions.
"""

adm2_results = []

# Get the size of the ADM2 collection
num_adm2_regions = adm2.size().getInfo()

# Convert the ADM2 FeatureCollection to a client-side list for iteration
adm2_list = adm2.toList(num_adm2_regions).getInfo()

print(f"Initialized adm2_results list. Found {num_adm2_regions} ADM2 regions for Kenya.")

"""## Calculate Population Statistics for Each ADM2

### Subtask:
For each ADM2 unit in Kenya, calculate the total, female, and male populations aged 60 and above for each year between 2015 and 2030. This involves filtering the WorldPop image collection by year, selecting the relevant age bands, summing them, and reducing the region by the ADM2 geometry.

**Reasoning**:
The subtask requires iterating through each ADM2 region and each year to calculate population statistics, which involves using nested loops, Earth Engine image operations, and reducing regions, as detailed in the instructions.
"""

for i in range(num_adm2_regions):
    adm2_feature = ee.Feature(adm2_list[i])
    adm2_name = adm2_feature.get("shapeName").getInfo()
    adm2_geometry = adm2_feature.geometry()

    print(f"Processing ADM2: {adm2_name} ({i + 1}/{num_adm2_regions})")

    for y in years:
        # Get the WorldPop image for the current year
        # The year_image_for_kenya function already filters to Kenya's overall boundary
        img = year_image_for_kenya(y)

        # Calculate population sums for the current ADM2 geometry
        female_img = img.select(female_60plus).reduce(ee.Reducer.sum()).rename("female_60plus")
        male_img   = img.select(male_60plus).reduce(ee.Reducer.sum()).rename("male_60plus")
        total_img  = female_img.add(male_img).rename("total_60plus")

        # Reduce region for the specific ADM2 geometry
        stats = total_img.addBands([female_img, male_img]).reduceRegion(
            reducer=ee.Reducer.sum(),
            geometry=adm2_geometry, # Use the specific ADM2 geometry
            scale=100, # 100m scale for population data
            bestEffort=True,
            maxPixels=1e13
        ).getInfo()

        adm2_results.append({
            "adm2_name": adm2_name,
            "year": y,
            "total_60plus": safe_float(stats.get("total_60plus")),
            "female_60plus": safe_float(stats.get("female_60plus")),
            "male_60plus": safe_float(stats.get("male_60plus")),
        })

"""**Reasoning**:
The previous code block successfully completed the iteration and population calculations for each ADM2 region. The next logical step, as per the original task, is to convert the accumulated `adm2_results` list into a pandas DataFrame, display its head, save it to a CSV file, and provide a download link.


"""

df_adm2 = pd.DataFrame(adm2_results)

print("\nDataFrame containing population statistics per ADM2 region:")
print(df_adm2.head())

csv_file_name = "kenya_adm2_60plus_population_2015-2030.csv"
df_adm2.to_csv(csv_file_name, index=False)
files.download(csv_file_name)

print(f"\nDownload complete: '{csv_file_name}'")

"""## Final Task

### Subtask:
Review the generated CSV file containing the population statistics for Kenya's ADM2 regions. The user can then proceed with any further analysis or visualization.

## Summary:

### Data Analysis Key Findings
*   The analysis successfully processed 290 ADM2 regions across Kenya.
*   Population statistics (total, female, and male aged 60 and above) were calculated for each ADM2 region for the years 2015 to 2030.
*   The WorldPop image collection was used with Earth Engine's `reduceRegion` function to aggregate population data at a 100m scale for each ADM2 geometry.
*   All calculated statistics were compiled into a pandas DataFrame.
*   A CSV file named `kenya_adm2_60plus_population_2015-2030.csv` was successfully generated and made available for download, containing the aggregated population data for all ADM2 regions and years.

### Insights or Next Steps
*   The generated CSV file provides a comprehensive dataset for demographic analysis of the aging population in Kenya at a granular administrative level, which can be valuable for targeted policy making and resource allocation.
*   The next step could involve loading this CSV into a data visualization tool or statistical software to identify regional trends, disparities, and growth patterns of the 60+ population in Kenya.
"""

import ee
import json
from google.colab import files

# Ensure ee is initialized, as it might not persist across sessions
try:
    ee.Initialize(project="ee-felixoluoch")
except Exception:
    ee.Authenticate()
    ee.Initialize(project="ee-felixoluoch")

# Redefine geoBoundaries FeatureCollections and kenya_shape_group
# to ensure they are available in this execution context
adm0 = ee.FeatureCollection("WM/geoLab/geoBoundaries/600/ADM0")
kenya_fc = adm0.filter(ee.Filter.eq("shapeName", "Kenya"))
kenya_shape_group = ee.String(kenya_fc.first().get("shapeGroup"))

adm2 = ee.FeatureCollection("WM/geoLab/geoBoundaries/600/ADM2").filter(
    ee.Filter.eq("shapeGroup", kenya_shape_group)
)

# Convert the ADM2 FeatureCollection to a GeoJSON object
adm2_geojson = adm2.getInfo()

# Add 'object_id' to each feature
for i, feature in enumerate(adm2_geojson['features']):
    feature['properties']['object_id'] = i + 1

# Serialize the modified GeoJSON object to a string
geojson_string = json.dumps(adm2_geojson)

# Define the filename for the GeoJSON file
geojson_file_name = "kenya_adm2_boundaries_indexed.geojson"

# Save the GeoJSON string to a file
with open(geojson_file_name, "w") as f:
    f.write(geojson_string)

# Provide a download link for the GeoJSON file
files.download(geojson_file_name)

print(f"Download complete: '{geojson_file_name}'")



import ee
import json
from google.colab import files

# Ensure ee is initialized, as it might not persist across sessions
try:
    ee.Initialize(project="ee-felixoluoch")
except Exception:
    ee.Authenticate()
    ee.Initialize(project="ee-felixoluoch")

# Load Kenya's ADM0 boundary to filter for ADM1 and ADM2
adm0 = ee.FeatureCollection("WM/geoLab/geoBoundaries/600/ADM0")
kenya_fc = adm0.filter(ee.Filter.eq("shapeName", "Kenya"))
kenya_shape_group = ee.String(kenya_fc.first().get("shapeGroup"))

# Load ADM1 boundaries for Kenya
adm1 = ee.FeatureCollection("WM/geoLab/geoBoundaries/600/ADM1").filter(
    ee.Filter.eq("shapeGroup", kenya_shape_group)
)

# Load ADM2 boundaries for Kenya
adm2 = ee.FeatureCollection("WM/geoLab/geoBoundaries/600/ADM2").filter(
    ee.Filter.eq("shapeGroup", kenya_shape_group)
)

# Combine ADM1 and ADM2 FeatureCollections
combined_adm_fc = adm1.merge(adm2)

# Convert the combined FeatureCollection to a GeoJSON object
combined_adm_geojson = combined_adm_fc.getInfo()

# Add 'object_id' to each feature and ensure ADM_NAME is present
for i, feature in enumerate(combined_adm_geojson['features']):
    feature['properties']['object_id'] = i + 1
    # Ensure ADM_NAME is set, using 'shapeName' as primary
    if 'ADM_NAME' not in feature['properties']:
        feature['properties']['ADM_NAME'] = feature['properties'].get('shapeName', 'Unknown')

# Serialize the modified GeoJSON object to a string
geojason_string = json.dumps(combined_adm_geojson)

# Define the filename for the GeoJSON file
geojason_file_name = "kenya_adm1_adm2_boundaries_indexed.geojson"

# Save the GeoJSON string to a file
with open(geojason_file_name, "w") as f:
    f.write(geojason_string)

# Provide a download link for the GeoJSON file
files.download(geojason_file_name)

print(f"Download complete: '{geojason_file_name}'")

"""# Task
Generate a CSV file named `kenya_adm2_0_4_population_2015-2030.csv` containing the total, female, and male populations aged 0-4 for each ADM2 region in Kenya from 2015 to 2030, based on the WorldPop dataset.

## Define 0-4 Age Bands

### Subtask:
Define the appropriate age bands for female and male populations aged 0-4 years from the WorldPop dataset.

**Reasoning**:
The subtask requires defining two lists, `female_0_4` and `male_0_4`, with the specified band names for age groups 0-4. This directly addresses the instructions by creating these lists.
"""

female_0_4 = [f'f_{i:02d}' for i in range(5)]
male_0_4 = [f'm_{i:02d}' for i in range(5)]

print("Female 0-4 age bands:", female_0_4)
print("Male 0-4 age bands:", male_0_4)

"""## Initialize Results List for 0-4 Population

### Subtask:
Initialize an empty list to store the calculated population statistics for children aged 0-4 for all ADM2 regions and years.

**Reasoning**:
Initialize an empty list named `adm2_0_4_results` to store the population statistics for the 0-4 age group as required by the subtask.
"""

adm2_0_4_results = []

print("Initialized empty list 'adm2_0_4_results'.")

import ee
import pandas as pd # Import pandas as it's used by safe_float and for potential DataFrame creation

# Ensure ee is initialized
try:
    ee.Initialize(project="ee-felixoluoch")
except Exception:
    ee.Authenticate()
    ee.Initialize(project="ee-felixoluoch")

# Redefine geoBoundaries FeatureCollections and related variables
adm0 = ee.FeatureCollection("WM/geoLab/geoBoundaries/600/ADM0")
kenya_fc = adm0.filter(ee.Filter.eq("shapeName", "Kenya"))
kenya_geom = kenya_fc.geometry()
kenya_shape_group = ee.String(kenya_fc.first().get("shapeGroup"))

adm2 = ee.FeatureCollection("WM/geoLab/geoBoundaries/600/ADM2").filter(
    ee.Filter.eq("shapeGroup", kenya_shape_group)
)

# Redefine WorldPop age-sex collection and related variables for `year_image_for_kenya`
agesex_ic = ee.ImageCollection("projects/sat-io/open-datasets/WORLDPOP/agesex")
first = ee.Image(agesex_ic.first())
has_year = "year" in first.propertyNames().getInfo()

def year_image_for_kenya(year: int) -> ee.Image:
    if has_year:
        ic_y = agesex_ic.filter(ee.Filter.eq("year", year))
    else:
        ic_y = agesex_ic.filter(ee.Filter.stringContains("system:index", str(year)))

    ic_y_ke = ic_y.filterBounds(kenya_geom)

    n_all = ic_y.size().getInfo()
    n_ke = ic_y_ke.size().getInfo()

    if n_ke == 0:
        raise ValueError(
            f"No images intersect Kenya for year={year}. "
            f"Images for that year in collection: {n_all}."
        )

    return ee.Image(ic_y_ke.mosaic())

def safe_float(x):
    return None if x is None else float(x)

# Redefine years list
years = list(range(2015, 2031))

# Corrected age bands for 0-4 based on available WorldPop bands
female_0_4 = ["f_00", "f_01"]
male_0_4 = ["m_00", "m_01"]

# Re-initialize num_adm2_regions and adm2_list before the loop
num_adm2_regions = adm2.size().getInfo()
adm2_list = adm2.toList(num_adm2_regions).getInfo()

# Initialize the results list, which was cleared in a previous step
adm2_0_4_results = []

for i in range(num_adm2_regions):
    adm2_feature = ee.Feature(adm2_list[i])
    adm2_name = adm2_feature.get("shapeName").getInfo()
    adm2_geometry = adm2_feature.geometry()

    print(f"Processing ADM2: {adm2_name} ({i + 1}/{num_adm2_regions})")

    for y in years:
        # Get the WorldPop image for the current year
        img = year_image_for_kenya(y)

        # Calculate population sums for the current ADM2 geometry for 0-4 age group
        female_0_4_img = img.select(female_0_4).reduce(ee.Reducer.sum()).rename("female_0_4")
        male_0_4_img   = img.select(male_0_4).reduce(ee.Reducer.sum()).rename("male_0_4")
        total_0_4_img  = female_0_4_img.add(male_0_4_img).rename("total_0_4")

        # Reduce region for the specific ADM2 geometry
        stats = total_0_4_img.addBands([female_0_4_img, male_0_4_img]).reduceRegion(
            reducer=ee.Reducer.sum(),
            geometry=adm2_geometry,
            scale=100,
            bestEffort=True,
            maxPixels=1e13
        ).getInfo()

        adm2_0_4_results.append({
            "adm2_name": adm2_name,
            "year": y,
            "total_0_4": safe_float(stats.get("total_0_4")),
            "female_0_4": safe_float(stats.get("female_0_4")),
            "male_0_4": safe_float(stats.get("male_0_4")),
        })

"""**Reasoning**:
The previous code block successfully completed the population calculations for each ADM2 region. The next step is to convert the accumulated `adm2_0_4_results` list into a pandas DataFrame, display its head, save it to a CSV file, and provide a download link, also ensuring `pandas` is imported as it was not defined in the previous attempt.


"""

import pandas as pd
from google.colab import files

df_adm2_0_4 = pd.DataFrame(adm2_0_4_results)

print("\nDataFrame containing 0-4 population statistics per ADM2 region:")
print(df_adm2_0_4.head())

csv_file_name = "kenya_adm2_0_4_population_2015-2030.csv"
df_adm2_0_4.to_csv(csv_file_name, index=False)
files.download(csv_file_name)

print(f"\nDownload complete: '{csv_file_name}'")



"""# Task
Define the age bands for male and female infants (0-12 months) and for women of reproductive age (15-49 years) based on WorldPop naming conventions.

## Load WorldPop Births and Pregnancies Data

### Subtask:
Identify and load the WorldPop births and pregnancies image collections. These will be used for calibration in later steps.

**Reasoning**:
The subtask requires loading two WorldPop image collections and inspecting their first images to confirm successful loading. This code block directly addresses these instructions by loading the specified collections and printing their first images.
"""

births_ic = ee.ImageCollection("WorldPop/GPWv4/UNFPA_2020/births")
pregnancies_ic = ee.ImageCollection("WorldPop/GPWv4/UNFPA_2020/pregnancies")

print("First image of WorldPop births collection:", births_ic.first().getInfo())
print("First image of WorldPop pregnancies collection:", pregnancies_ic.first().getInfo())

"""**Reasoning**:
The previous code failed because the specified Earth Engine assets for WorldPop births and pregnancies were not found. I will replace them with publicly available WorldPop assets from the `WorldPop/WP_GLOBAL_1KM_ANNUAL` collection that represent population aged 0 (as a proxy for births) and female population aged 15-49 (as a proxy for women of reproductive age/pregnancies), ensuring `ee.ImageCollection` objects are still created.


"""

def get_age_0_pop(image):
    # Select f_00 and m_00 bands and sum them for age 0 population
    return image.select(['f_00', 'm_00']).reduce(ee.Reducer.sum()).rename('total_0_pop').copyProperties(image, ['system:time_start', 'year'])

def get_female_15_49_pop(image):
    # Correctly select 5-year grouped bands for female population aged 15-49
    female_15_49_bands = ['f_15', 'f_20', 'f_25', 'f_30', 'f_35', 'f_40', 'f_45']
    # Select these bands and sum them for women of reproductive age
    return image.select(female_15_49_bands).reduce(ee.Reducer.sum()).rename('female_15_49_pop').copyProperties(image, ['system:time_start', 'year'])

# Apply these functions to the existing agesex_ic
births_ic = agesex_ic.map(get_age_0_pop)
pregnancies_ic = agesex_ic.map(get_female_15_49_pop)

print("First image of WorldPop births (age 0 population) collection:", births_ic.first().getInfo())
print("First image of WorldPop pregnancies (female 15-49 population) collection:", pregnancies_ic.first().getInfo())

"""## Define Age and Event Band Lists

### Subtask:
Define Python lists for female/male 0-12 months (infants) bands, female 15-49 years (WRA) bands, and band names for WorldPop births and pregnancies, based on WorldPop naming conventions.

**Reasoning**:
The subtask requires defining three Python lists: `infant_female_bands` for female infants (0-12 months), `infant_male_bands` for male infants (0-12 months), and `wra_female_bands` for women of reproductive age (15-49 years), adhering to WorldPop's 5-year grouped band naming conventions as observed in the `agesex_ic` dataset.
"""

infant_female_bands = ['f_00']
infant_male_bands = ['m_00']
wra_female_bands = ['f_15', 'f_20', 'f_25', 'f_30', 'f_35', 'f_40', 'f_45']

print("Infant Female Bands (0-12 months):", infant_female_bands)
print("Infant Male Bands (0-12 months):", infant_male_bands)
print("Women of Reproductive Age (15-49) Bands:", wra_female_bands)

"""## Initialize Results and Anchor Year Data Structures

### Subtask:
Initialize empty lists to store all intermediate and final results per ADM2 per year (infants, WRA, births, pregnancies), and data structures to store national totals for anchor years for calibration purposes.

**Reasoning**:
Initialize the required empty lists and dictionaries, and define the anchor years list as per the subtask instructions to prepare data structures for subsequent calculations.
"""

adm2_infants_results = []
adm2_wra_results = []
adm2_births_results = []
adm2_pregnancies_results = []

anchor_years = [2015, 2020, 2025, 2030]

national_infants_anchor_year_totals = {}
national_births_anchor_year_totals = {}
national_pregnancies_anchor_year_totals = {}

print("Initialized all results lists and anchor year data structures.")

"""## Calculate Zonal Statistics for Infants, WRA, WorldPop Births, and WorldPop Pregnancies per ADM2

### Subtask:
Loop through each ADM2 region and each year (2015-2030) to calculate population statistics for infants (0-12 months) and women of reproductive age (15-49 years). Additionally, for anchor years (2015, 2020, 2025, 2030), calculate zonal sums for WorldPop births and pregnancies data per ADM2.

**Reasoning**:
The subtask requires iterating through each ADM2 region and each year, calculating population statistics for infants and women of reproductive age, and conditionally calculating statistics for WorldPop births and pregnancies for anchor years. The code block directly implements these instructions using nested loops and Earth Engine operations.
"""

for i in range(num_adm2_regions):
    adm2_feature = ee.Feature(adm2_list[i])
    adm2_name = adm2_feature.get('shapeName').getInfo()
    adm2_geometry = adm2_feature.geometry()

    print(f"Processing ADM2: {adm2_name} ({i + 1}/{num_adm2_regions})")

    for y in years:
        # Get the WorldPop image for the current year
        img = year_image_for_kenya(y)

        # Calculate infant population (0-12 months)
        female_infants_img = img.select(infant_female_bands).reduce(ee.Reducer.sum()).rename("female_infants")
        male_infants_img   = img.select(infant_male_bands).reduce(ee.Reducer.sum()).rename("male_infants")
        total_infants_img  = female_infants_img.add(male_infants_img).rename("total_infants")

        infant_stats = total_infants_img.addBands([female_infants_img, male_infants_img]).reduceRegion(
            reducer=ee.Reducer.sum(),
            geometry=adm2_geometry,
            scale=100,
            bestEffort=True,
            maxPixels=1e13
        ).getInfo()

        adm2_infants_results.append({
            "adm2_name": adm2_name,
            "year": y,
            "total_infants": safe_float(infant_stats.get("total_infants")),
            "female_infants": safe_float(infant_stats.get("female_infants")),
            "male_infants": safe_float(infant_stats.get("male_infants")),
        })

        # Calculate Women of Reproductive Age (15-49 years) population
        wra_img = img.select(wra_female_bands).reduce(ee.Reducer.sum()).rename("total_wra")

        wra_stats = wra_img.reduceRegion(
            reducer=ee.Reducer.sum(),
            geometry=adm2_geometry,
            scale=100,
            bestEffort=True,
            maxPixels=1e13
        ).getInfo()

        adm2_wra_results.append({
            "adm2_name": adm2_name,
            "year": y,
            "total_wra": safe_float(wra_stats.get("total_wra")),
        })

        # Process for anchor years for births and pregnancies
        if y in anchor_years:
            # Births data for anchor year
            births_img_year_filtered = births_ic.filter(ee.Filter.eq('year', y)).first()
            if births_img_year_filtered:
                births_stats = births_img_year_filtered.reduceRegion(
                    reducer=ee.Reducer.sum(),
                    geometry=adm2_geometry,
                    scale=100,
                    bestEffort=True,
                    maxPixels=1e13
                ).getInfo()
                adm2_births_results.append({
                    "adm2_name": adm2_name,
                    "year": y,
                    "total_births": safe_float(births_stats.get("total_0_pop")),
                })
            else:
                print(f"Warning: No births image found for year {y} in ADM2 {adm2_name}")
                adm2_births_results.append({
                    "adm2_name": adm2_name,
                    "year": y,
                    "total_births": None,
                })

            # Pregnancies data for anchor year
            pregnancies_img_year_filtered = pregnancies_ic.filter(ee.Filter.eq('year', y)).first()
            if pregnancies_img_year_filtered:
                pregnancies_stats = pregnancies_img_year_filtered.reduceRegion(
                    reducer=ee.Reducer.sum(),
                    geometry=adm2_geometry,
                    scale=100,
                    bestEffort=True,
                    maxPixels=1e13
                ).getInfo()
                adm2_pregnancies_results.append({
                    "adm2_name": adm2_name,
                    "year": y,
                    "total_pregnancies": safe_float(pregnancies_stats.get("female_15_49_pop")),
                })
            else:
                print(f"Warning: No pregnancies image found for year {y} in ADM2 {adm2_name}")
                adm2_pregnancies_results.append({
                    "adm2_name": adm2_name,
                    "year": y,
                    "total_pregnancies": None,
                })



"""# Task
Export the `adm2_infants_results`, `adm2_wra_results`, `adm2_births_results`, and `adm2_pregnancies_results` lists into pandas DataFrames and save them as separate CSV files. Provide download links for each file. Note that births and pregnancies data will only be for anchor years at this stage.

## Export Intermediate Results to CSV

### Subtask:
Convert the `adm2_infants_results`, `adm2_wra_results`, `adm2_births_results`, and `adm2_pregnancies_results` lists into pandas DataFrames and save them as separate CSV files. Provide download links for each file. Note that births and pregnancies data will only be for anchor years at this stage.

**Reasoning**:
The subtask requires converting four lists (`adm2_infants_results`, `adm2_wra_results`, `adm2_births_results`, and `adm2_pregnancies_results`) into pandas DataFrames, displaying their heads, and then saving each DataFrame to a separate CSV file with a download link. This single code block will handle all these operations sequentially.
"""

import pandas as pd
from google.colab import files

# 1. Infants data
df_infants = pd.DataFrame(adm2_infants_results)
print("\nDataFrame containing infants population statistics per ADM2 region:")
print(df_infants.head())
csv_file_name_infants = "kenya_adm2_infants_2015-2030.csv"
df_infants.to_csv(csv_file_name_infants, index=False)
files.download(csv_file_name_infants)
print(f"\nDownload complete: '{csv_file_name_infants}'")

# 2. Women of Reproductive Age (WRA) data
df_wra = pd.DataFrame(adm2_wra_results)
print("\nDataFrame containing WRA population statistics per ADM2 region:")
print(df_wra.head())
csv_file_name_wra = "kenya_adm2_wra_2015-2030.csv"
df_wra.to_csv(csv_file_name_wra, index=False)
files.download(csv_file_name_wra)
print(f"\nDownload complete: '{csv_file_name_wra}'")

# 3. Births (anchor years) data
df_births_anchor_years = pd.DataFrame(adm2_births_results)
print("\nDataFrame containing births statistics for anchor years per ADM2 region:")
print(df_births_anchor_years.head())
csv_file_name_births = "kenya_adm2_births_anchor_years.csv"
df_births_anchor_years.to_csv(csv_file_name_births, index=False)
files.download(csv_file_name_births)
print(f"\nDownload complete: '{csv_file_name_births}'")

# 4. Pregnancies (anchor years) data
df_pregnancies_anchor_years = pd.DataFrame(adm2_pregnancies_results)
print("\nDataFrame containing pregnancies statistics for anchor years per ADM2 region:")
print(df_pregnancies_anchor_years.head())
csv_file_name_pregnancies = "kenya_adm2_pregnancies_anchor_years.csv"
df_pregnancies_anchor_years.to_csv(csv_file_name_pregnancies, index=False)
files.download(csv_file_name_pregnancies)
print(f"\nDownload complete: '{csv_file_name_pregnancies}'")

"""## Aggregate National Totals for Anchor Years

### Subtask:
Aggregate the subcounty infant totals to get national infant totals for anchor years. Similarly, aggregate the subcounty WorldPop births and pregnancies totals to get national totals for anchor years.

**Reasoning**:
The subtask requires aggregating subcounty totals to national totals for infants, births, and pregnancies for the anchor years. This involves filtering the respective DataFrames by anchor years, grouping by year, summing the relevant columns, and storing the results in the designated dictionaries.
"""

national_infants_anchor_year_totals = {}
filtered_infants = df_infants[df_infants['year'].isin(anchor_years)]
for year, group in filtered_infants.groupby('year'):
    national_infants_anchor_year_totals[year] = group['total_infants'].sum()

national_births_anchor_year_totals = {}
for year, group in df_births_anchor_years.groupby('year'):
    national_births_anchor_year_totals[year] = group['total_births'].sum()

national_pregnancies_anchor_year_totals = {}
for year, group in df_pregnancies_anchor_years.groupby('year'):
    national_pregnancies_anchor_year_totals[year] = group['total_pregnancies'].sum()

print("National Infant Totals for Anchor Years:", national_infants_anchor_year_totals)
print("National Births Totals for Anchor Years:", national_births_anchor_year_totals)
print("National Pregnancies Totals for Anchor Years:", national_pregnancies_anchor_year_totals)

"""## Calculate and Interpolate Kappa (Births Calibration Factor)

### Subtask:
For each anchor year, calculate the national births calibration factor 'kappa' as `National_WorldPop_Births / National_Infants`. Linearly interpolate these 'kappa' values for all years between 2015 and 2030.

**Reasoning**:
To calculate and interpolate the kappa values as per the subtask, I need to first calculate kappa for anchor years and then use linear interpolation for all years between 2015 and 2030. This requires importing the `numpy` library for the interpolation step.
"""

import numpy as np

# 1. Create an empty dictionary to store kappa for anchor years
kappa_anchor_years = {}

# 2. Iterate through each year in anchor_years
for year in anchor_years:
    # 3. Retrieve national total births and infants
    national_births_total = national_births_anchor_year_totals.get(year, 0)
    national_infants_total = national_infants_anchor_year_totals.get(year, 0)

    # 4. Calculate kappa for the current year, handling division by zero
    if national_infants_total > 0:
        kappa = national_births_total / national_infants_total
    else:
        kappa = 0  # Assign 0 if national_infants_total is zero
    kappa_anchor_years[year] = kappa

# 5. Create a list of all years from 2015 to 2030
all_years = list(range(2015, 2031))

# Prepare data for interpolation
anchor_years_np = np.array(list(kappa_anchor_years.keys()))
kappa_values_np = np.array(list(kappa_anchor_years.values()))

# 6. Using the kappa_anchor_years data, create a linear interpolation function for kappa
# 7. Apply the interpolation function to all_years to get interpolated kappa values
kappas_interpolated = np.interp(all_years, anchor_years_np, kappa_values_np)
kappa_interpolated_yearly = dict(zip(all_years, kappas_interpolated))

# 8. Print the dictionaries
print("Kappa for Anchor Years:", kappa_anchor_years)
print("Interpolated Kappa Values for All Years (2015-2030):")
for year, value in kappa_interpolated_yearly.items():
    print(f"  {year}: {value:.4f}")

"""## Calculate and Interpolate R (Pregnancies to Births Ratio)

### Subtask:
For each anchor year, calculate the national pregnancies to births ratio 'r' as `National_WorldPop_Pregnancies / National_WorldPop_Births`. Linearly interpolate these 'r' values for all years between 2015 and 2030.

**Reasoning**:
The previous code generated zero values for national births and pregnancies, which prevents the meaningful calculation of the 'r' ratio. This was due to an inefficient way of accessing the population data for 'births' (age 0) and 'pregnancies' (women of reproductive age) from the WorldPop `agesex_ic` within the loop. To fix this, I will modify the loop to directly extract these population statistics from the `img` (which is already filtered to Kenya's geometry by `year_image_for_kenya`) for anchor years, ensuring non-zero values are used for calibration.

# Task
**Task**: Load the national anchor year data for births and pregnancies from the provided Excel file (`/content/birthsAndPregnanciesKEN.xlsx`) into a pandas DataFrame. Extract the relevant national total births and pregnancies for the anchor years (2015, 2020, 2025, 2030) and store them in `national_births_anchor_year_totals` and `national_pregnancies_anchor_year_totals`.

## Load Infants and WRA Data from CSVs

### Subtask:
Load the pre-computed infants data from '/content/kenya_adm2_infants_2015-2030.csv' and WRA data from '/content/kenya_adm2_wra_2015-2030.csv' into pandas DataFrames (`df_infants` and `df_wra`) for use in subsequent steps.

**Reasoning**:
The subtask requires loading two CSV files into pandas DataFrames, so I will use `pd.read_csv` for each file and then display the head of both DataFrames to verify the loading.
"""

import pandas as pd

# Load infants data
df_infants = pd.read_csv('/content/kenya_adm2_infants_2015-2030.csv')
print("df_infants head:")
print(df_infants.head())

# Load WRA data
df_wra = pd.read_csv('/content/kenya_adm2_wra_2015-2030.csv')
print("\ndf_wra head:")
print(df_wra.head())

"""## Load National Anchor Births and Pregnancies Data from Excel

### Subtask:
Load the national anchor year data for births and pregnancies from the provided Excel file (`/content/birthsAndPregnanciesKEN.xlsx`) into a pandas DataFrame. Extract the relevant national total births and pregnancies for the anchor years (2015, 2020, 2025, 2030).

**Reasoning**:
The subtask requires loading an Excel file into a pandas DataFrame, filtering it by anchor years, and then extracting national totals for births and pregnancies into dictionaries for those years.
"""

import pandas as pd

# Load the Excel file
df_national_data = pd.read_excel('/content/birthsAndPregnanciesKEN.xlsx')
print("National data from Excel file:")
print(df_national_data.head())

# Initialize dictionaries
national_births_anchor_year_totals = {}
national_pregnancies_anchor_year_totals = {}

# Populate dictionaries with national totals for anchor years
# The Excel file contains columns like 'adjustedBirths2015', 'pregnancies2015', etc.
for year in anchor_years:
    births_col_name = f'adjustedBirths{year}'
    pregnancies_col_name = f'pregnancies{year}'

    if births_col_name in df_national_data.columns:
        national_births_anchor_year_totals[year] = df_national_data[births_col_name].sum()
    else:
        print(f"Warning: Births column '{births_col_name}' not found for year {year}.")
        national_births_anchor_year_totals[year] = 0.0

    if pregnancies_col_name in df_national_data.columns:
        national_pregnancies_anchor_year_totals[year] = df_national_data[pregnancies_col_name].sum()
    else:
        print(f"Warning: Pregnancies column '{pregnancies_col_name}' not found for year {year}.")
        national_pregnancies_anchor_year_totals[year] = 0.0

print("\nNational Births Totals for Anchor Years:", national_births_anchor_year_totals)
print("National Pregnancies Totals for Anchor Years:", national_pregnancies_anchor_year_totals)

"""**Reasoning**:
The previous step successfully retrieved the national births and pregnancies totals for anchor years from the Excel file. Now, the subtask requires calculating the 'r' ratio (pregnancies to births) for these anchor years and then linearly interpolating these values for all years between 2015 and 2030. This involves iterating through anchor years, performing division, and then using NumPy for interpolation.


"""

import numpy as np

# 1. Create an empty dictionary to store r for anchor years
r_anchor_years = {}

# 2. Iterate through each year in anchor_years
for year in anchor_years:
    # 3. Retrieve national total pregnancies and births
    national_pregnancies_total = national_pregnancies_anchor_year_totals.get(year, 0)
    national_births_total = national_births_anchor_year_totals.get(year, 0)

    # 4. Calculate r for the current year, handling division by zero
    if national_births_total > 0:
        r = national_pregnancies_total / national_births_total
    else:
        r = 0  # Assign 0 if national_births_total is zero
    r_anchor_years[year] = r

# 5. Create a list of all years from 2015 to 2030
all_years = list(range(2015, 2031))

# Prepare data for interpolation
anchor_years_np = np.array(list(r_anchor_years.keys()))
r_values_np = np.array(list(r_anchor_years.values()))

# 6. Using the r_anchor_years data, create a linear interpolation function for r
# 7. Apply the interpolation function to all_years to get interpolated r values
r_interpolated = np.interp(all_years, anchor_years_np, r_values_np)
r_interpolated_yearly = dict(zip(all_years, r_interpolated))

# 8. Print the dictionaries
print("R for Anchor Years:", r_anchor_years)
print("Interpolated R Values for All Years (2015-2030):")
for year, value in r_interpolated_yearly.items():
    print(f"  {year}: {value:.4f}")

"""## Aggregate National Infant Totals for Anchor Years

### Subtask:
Aggregate the subcounty infant totals from the loaded `df_infants` to get national infant totals for anchor years. Store these in `national_infants_anchor_year_totals`.

**Reasoning**:
To aggregate the subcounty infant totals to national totals for the anchor years, I will filter the `df_infants` DataFrame, group by year, sum the `total_infants` column, and store the results in the `national_infants_anchor_year_totals` dictionary as instructed.
"""

national_infants_anchor_year_totals = {}
filtered_infants = df_infants[df_infants['year'].isin(anchor_years)]
for year, group in filtered_infants.groupby('year'):
    national_infants_anchor_year_totals[year] = group['total_infants'].sum()

print("National Infant Totals for Anchor Years:", national_infants_anchor_year_totals)

"""## Calculate and Interpolate Kappa (Births Calibration Factor)

### Subtask:
For each anchor year, calculate the national births calibration factor 'kappa' as `National_Births_from_Excel / National_Infants`. Linearly interpolate these 'kappa' values for all years between 2015 and 2030.

**Reasoning**:
To calculate and interpolate the kappa values as per the subtask, I need to first calculate kappa for anchor years and then use linear interpolation for all years between 2015 and 2030. This requires importing the `numpy` library for the interpolation step.
"""

import numpy as np

# 1. Create an empty dictionary to store kappa for anchor years
kappa_anchor_years = {}

# 2. Iterate through each year in anchor_years
for year in anchor_years:
    # 3. Retrieve national total births and infants
    national_births_total = national_births_anchor_year_totals.get(year, 0)
    national_infants_total = national_infants_anchor_year_totals.get(year, 0)

    # 4. Calculate kappa for the current year, handling division by zero
    if national_infants_total > 0:
        kappa = national_births_total / national_infants_total
    else:
        kappa = 0  # Assign 0 if national_infants_total is zero
    kappa_anchor_years[year] = kappa

# 5. Create a list of all years from 2015 to 2030
all_years = list(range(2015, 2031))

# Prepare data for interpolation
anchor_years_np = np.array(list(kappa_anchor_years.keys()))
kappa_values_np = np.array(list(kappa_anchor_years.values()))

# 6. Using the kappa_anchor_years data, create a linear interpolation function for kappa
# 7. Apply the interpolation function to all_years to get interpolated kappa values
kappas_interpolated = np.interp(all_years, anchor_years_np, kappa_values_np)
kappa_interpolated_yearly = dict(zip(all_years, kappas_interpolated))

# 8. Print the dictionaries
print("Kappa for Anchor Years:", kappa_anchor_years)
print("Interpolated Kappa Values for All Years (2015-2030):")
for year, value in kappa_interpolated_yearly.items():
    print(f"  {year}: {value:.4f}")

"""## Calculate and Interpolate R (Pregnancies to Births Ratio)

### Subtask:
For each anchor year, calculate the national pregnancies to births ratio 'r' as `National_Pregnancies_from_Excel / National_Births_from_Excel`. Linearly interpolate these 'r' values for all years between 2015 and 2030.

**Reasoning**:
The subtask requires calculating the 'r' ratio (pregnancies to births) for the anchor years and then linearly interpolating these values for all years between 2015 and 2030, which involves iterating through anchor years, performing division, and then using NumPy for interpolation. The necessary data is available in the kernel.
"""

import numpy as np

# 1. Create an empty dictionary to store r for anchor years
r_anchor_years = {}

# 2. Iterate through each year in anchor_years
for year in anchor_years:
    # 3. Retrieve national total pregnancies and births
    national_pregnancies_total = national_pregnancies_anchor_year_totals.get(year, 0)
    national_births_total = national_births_anchor_year_totals.get(year, 0)

    # 4. Calculate r for the current year, handling division by zero
    if national_births_total > 0:
        r = national_pregnancies_total / national_births_total
    else:
        r = 0  # Assign 0 if national_births_total is zero
    r_anchor_years[year] = r

# 5. Create a list of all years from 2015 to 2030
all_years = list(range(2015, 2031))

# Prepare data for interpolation
anchor_years_np = np.array(list(r_anchor_years.keys()))
r_values_np = np.array(list(r_anchor_years.values()))

# 6. Using the r_anchor_years data, create a linear interpolation function for r
# 7. Apply the interpolation function to all_years to get interpolated r values
r_interpolated = np.interp(all_years, anchor_years_np, r_values_np)
r_interpolated_yearly = dict(zip(all_years, r_interpolated))

# 8. Print the dictionaries
print("R for Anchor Years:", r_anchor_years)
print("Interpolated R Values for All Years (2015-2030):")
for year, value in r_interpolated_yearly.items():
    print(f"  {year}: {value:.4f}")

"""## Calculate Subcounty WRA Shares and Estimated Annual Births

### Subtask:
For each year, calculate the subcounty Women of Reproductive Age (WRA) share (`pi_s,y`) using `df_wra`. Then, for each subcounty and year, calculate the estimated annual births (`B_hat_s,y`) using the formula: `(kappa_y * National_Infants_y) * pi_s,y`.

**Reasoning**:
First, I'll calculate the national total WRA for each year by grouping 'df_wra' by year and summing 'total_wra', which is the first step in calculating the subcounty WRA share.
"""

national_wra_yearly_totals = df_wra.groupby('year')['total_wra'].sum().to_dict()

print("National WRA Totals Per Year:")
for year, total in national_wra_yearly_totals.items():
    print(f"  {year}: {total:.2f}")

"""**Reasoning**:
Now that national WRA totals are available, the next logical step according to the instructions is to calculate the subcounty WRA share (`pi_s,y`) for each row in `df_wra`. This involves merging the `national_wra_yearly_totals` into `df_wra` based on the 'year' column, and then performing the division.


"""

df_wra['national_wra_total'] = df_wra['year'].map(national_wra_yearly_totals)
df_wra['pi_s_y'] = df_wra['total_wra'] / df_wra['national_wra_total']

print("DataFrame with subcounty WRA shares (pi_s_y):")
print(df_wra.head())

"""**Reasoning**:
The next step is to create a new column `kappa_y` in `df_wra` by mapping the `kappa_interpolated_yearly` values to the `year` column, as per the subtask instructions.


"""

df_wra['kappa_y'] = df_wra['year'].map(kappa_interpolated_yearly)

print("DataFrame with kappa_y column:")
print(df_wra.head())

"""**Reasoning**:
The next step is to create a new column for `National_Infants_y` in `df_wra` by mapping the national infant totals to the `year` column. Since `national_infants_anchor_year_totals` only contains data for anchor years, I need to interpolate these values for all years from 2015 to 2030 first.


"""

import numpy as np

# Prepare data for interpolation of national infant totals
anchor_years_np_infants = np.array(list(national_infants_anchor_year_totals.keys()))
infant_values_np = np.array(list(national_infants_anchor_year_totals.values()))

# Interpolate national infant totals for all years
all_years = list(range(2015, 2031))
infants_interpolated = np.interp(all_years, anchor_years_np_infants, infant_values_np)
national_infants_yearly = dict(zip(all_years, infants_interpolated))

# Map the interpolated national infant totals to df_wra
df_wra['National_Infants_y'] = df_wra['year'].map(national_infants_yearly)

print("DataFrame with National_Infants_y column (interpolated):")
print(df_wra.head())

"""**Reasoning**:
All necessary components (`kappa_y`, `National_Infants_y`, and `pi_s,y`) are available in the `df_wra` DataFrame. The next step is to calculate the estimated annual births (`B_hat_s,y`) using the provided formula and add it as a new column.


"""

df_wra['B_hat_s_y'] = df_wra['kappa_y'] * df_wra['National_Infants_y'] * df_wra['pi_s_y']

print("DataFrame with Estimated Annual Births (B_hat_s_y):")
print(df_wra.head())

"""## Calculate Estimated Annual Pregnancies per Subcounty

### Subtask:
For each subcounty and year, calculate the estimated annual pregnancies (P_hat_s,y) using the formula: r_y * B_hat_s,y.

**Reasoning**:
First, I'll add a new column named 'r_y' to the `df_wra` DataFrame by mapping the `r_interpolated_yearly` dictionary to the 'year' column, as the `r_y` value is needed for calculating the estimated annual pregnancies.
"""

df_wra['r_y'] = df_wra['year'].map(r_interpolated_yearly)

print("DataFrame with r_y column:")
print(df_wra.head())

"""**Reasoning**:
Now that the 'r_y' and 'B_hat_s_y' columns are available in `df_wra`, I will calculate the estimated annual pregnancies ('P_hat_s_y') by multiplying these two columns, and then display the head of the DataFrame to show the new column.


"""

df_wra['P_hat_s_y'] = df_wra['r_y'] * df_wra['B_hat_s_y']

print("DataFrame with Estimated Annual Pregnancies (P_hat_s_y):")
print(df_wra.head())

"""## Compile Results into DataFrame and Export to CSV

### Subtask:
Combine all calculated results (infants, WRA, estimated births, estimated pregnancies) into a pandas DataFrame. Export this DataFrame to a CSV file named `kenya_subcounty_population_and_events_2015-2030.csv` and provide a download link. Additionally, confirm the availability of the `.geojson` file with the geometries and `ADM2_NAME` and `object_id` as properties.

**Reasoning**:
The subtask requires merging `df_infants` with `df_wra` to create a `df_combined_results` DataFrame. This involves selecting specific columns from each DataFrame that are relevant for the final output and performing a merge operation on 'adm2_name' and 'year'.
"""

df_combined_results = pd.merge(
    df_infants[['adm2_name', 'year', 'total_infants', 'female_infants', 'male_infants']],
    df_wra[['adm2_name', 'year', 'total_wra', 'B_hat_s_y', 'P_hat_s_y']],
    on=['adm2_name', 'year'],
    how='inner'
)

print("Combined DataFrame (df_combined_results) head:")
print(df_combined_results.head())

"""**Reasoning**:
The previous merge operation resulted in duplicate rows in `df_combined_results`, indicating that one or both of the input DataFrames (`df_infants`, `df_wra`) might contain duplicate entries for the 'adm2_name' and 'year' combination. To resolve this, I will first remove any duplicates from `df_infants` and `df_wra` based on these key columns before merging them. After cleaning the data, I will proceed with the merge, display the head of the combined DataFrame, save it to a CSV file, and provide a download link as per the subtask requirements.


"""

import pandas as pd
from google.colab import files

# Remove duplicates from df_infants and df_wra based on 'adm2_name' and 'year'
# This is necessary because some previous operations (like mapping interpolated values) might have created duplicates
df_infants_cleaned = df_infants.drop_duplicates(subset=['adm2_name', 'year']).copy()
df_wra_cleaned = df_wra.drop_duplicates(subset=['adm2_name', 'year']).copy()

# Merge the cleaned DataFrames
df_combined_results = pd.merge(
    df_infants_cleaned[['adm2_name', 'year', 'total_infants', 'female_infants', 'male_infants']],
    df_wra_cleaned[['adm2_name', 'year', 'total_wra', 'B_hat_s_y', 'P_hat_s_y']],
    on=['adm2_name', 'year'],
    how='inner'
)

print("Combined DataFrame (df_combined_results) head after removing duplicates:")
print(df_combined_results.head())

# Save the combined DataFrame to a CSV file
csv_file_name_combined = "kenya_subcounty_population_and_events_2015-2030.csv"
df_combined_results.to_csv(csv_file_name_combined, index=False)

# Provide a download link for the CSV file
files.download(csv_file_name_combined)

print(f"\nDownload complete: '{csv_file_name_combined}'")

# Confirm the GeoJSON file, which was generated in a previous step.
# The file 'kenya_adm2_boundaries_indexed.geojson' should be available in the /content/ directory.
# We are just confirming its existence here as part of the task.
import os
geoj_file = 'kenya_adm2_boundaries_indexed.geojson'
if os.path.exists(f'/content/{geoj_file}'):
    print(f"\nConfirmed: The GeoJSON file '{geoj_file}' is available.")
else:
    print(f"\nWarning: The GeoJSON file '{geoj_file}' was not found. It should have been generated in a previous step.")

"""## Compile Results into DataFrame and Export to CSV

### Subtask:
Regenerate the GeoJSON file for Kenya's ADM2 boundaries with 'object_id' properties, ensuring its availability for further analysis or visualization.

**Reasoning**:
To regenerate the GeoJSON file with 'object_id' properties, I need to re-execute the Earth Engine operations to filter the ADM2 boundaries for Kenya, add the 'object_id' to each feature, and then save and provide a download link for the GeoJSON file. This step replicates the functionality of a previous cell (`4cc40d00`) to ensure the file is correctly generated as part of the current subtask.
"""

import ee
import json
from google.colab import files

# Ensure ee is initialized, as it might not persist across sessions
try:
    ee.Initialize(project="ee-felixoluoch")
except Exception:
    ee.Authenticate()
    ee.Initialize(project="ee-felixoluoch")

# Redefine geoBoundaries FeatureCollections and kenya_shape_group
# to ensure they are available in this execution context
adm0 = ee.FeatureCollection("WM/geoLab/geoBoundaries/600/ADM0")
kenya_fc = adm0.filter(ee.Filter.eq("shapeName", "Kenya"))
kenya_shape_group = ee.String(kenya_fc.first().get("shapeGroup"))

adm2 = ee.FeatureCollection("WM/geoLab/geoBoundaries/600/ADM2").filter(
    ee.Filter.eq("shapeGroup", kenya_shape_group)
)

# Convert the ADM2 FeatureCollection to a GeoJSON object
adm2_geojson = adm2.getInfo()

# Add 'object_id' to each feature
for i, feature in enumerate(adm2_geojson['features']):
    feature['properties']['object_id'] = i + 1

# Serialize the modified GeoJSON object to a string
geojson_string = json.dumps(adm2_geojson)

# Define the filename for the GeoJSON file
geojson_file_name = "kenya_adm2_boundaries_indexed.geojson"

# Save the GeoJSON string to a file
with open(geojson_file_name, "w") as f:
    f.write(geojson_string)

# Provide a download link for the GeoJSON file
files.download(geojson_file_name)

print(f"Download complete: '{geojson_file_name}'")
